# some more ls aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vim='vim -p'
alias ll='ls -al'
alias la='ls -A'

[ command -v act &>/dev/null ] || alias act='act --container-architecture linux/amd64'
[ command -v sqlformat &>/dev/null ] || alias pretty-sql='sqlformat --reindent --keywords upper --identifiers lower'
[ command -v nvim &>/dev/null ] || alias vim='nvim -p'

# customized alias for Darwin
if [ `uname` = Darwin -o "$TERM_PROGRAM" = Apple_Terminal ]; then
	alias ls='ls -w'
fi

# vim: ft=bash:
