apiVersion: networking.istio.io/v1beta1
kind: Gateway

metadata:
  name: ${ name }
  namespace: ${ namespace }
  labels:
    app: ${ name }
    service: others

spec:
  selector:
    istio: gateway

  servers:
    - hosts:
        - "*"
      port:
        name: ${ name }
        number: ${ service_port }
        protocol: TCP
