---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: ${ name }
  namespace: ${ namespace }
  labels:
    app: ${ name }
    service: http
spec:
  replicas: 1

  selector:
    matchLabels:
      app: ${ name }
      service: http
  template:
    metadata:
      labels:
        app: ${ name }
        service: http
    spec:
      containers:
        - name: ${ name }
          image: ${ image }:${ image_tag }
          ports:
            - containerPort: ${ port }
              protocol: TCP
          env:
            - name: REGISTRY_HTTP_ADDR
              value: ":${ port }"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
