---
service:
  type: LoadBalancer
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: ssh
      port: 2222
      protocol: TCP
      targetPort: 2222
    - name: dns
      port: 53
      protocol: TCP
      targetPort: 53
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
