---
- name: Settings - install the DEV environment
  hosts:
    - homebrew

  tasks:
    - name: Homebrew - install basic dependency
      community.general.homebrew:
        state: present
        name:
          - tree
          - wget
          - cloc
          - htop
          - watch
    - name: Homebrew - install languages
      community.general.homebrew:
        state: present
        name:
          - go
          - rust
          - k6
    - name: Homebrew - upgrade all packages
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

  roles:
    - role: editor
