---
- name: Settings - install the DEV environment
  hosts: homebrew

  tasks:
    - name: Homebrew - upgrade all packages
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
